# Generated by Django 5.0.2 on 2024-02-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muzqaymoqlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('turi', models.CharField(max_length=100)),
                ('ishlab_ch_sana', models.DateTimeField()),
                ('yaroqlilik_muddati', models.DateTimeField()),
                ('sqladdagi_soni', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
