# Generated by Django 5.0.2 on 2024-02-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_muzqaymoqlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hodimlar_00',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('tel_raqam', models.CharField(max_length=100)),
                ('ish_boshlagan_sana', models.DateTimeField()),
                ('ishlagan_kunlar_soni', models.DecimalField(decimal_places=0, max_digits=10000)),
                ('belgilangan_narx', models.IntegerField(blank=True, null=True)),
                ('karta', models.CharField(max_length=100)),
                ('Bank_Tranzit', models.CharField(max_length=100)),
                ('bank_mfo', models.CharField(max_length=100)),
            ],
        ),
    ]
