# Generated by Django 5.0.2 on 2024-02-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_hodimlar_00'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izoh_011',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzusi', models.CharField(max_length=100)),
                ('izohi', models.TextField()),
            ],
        ),
    ]
